services:
  app:
    build: .
    container_name: my-python-app
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/config.yaml
      - ./output:/output
    command: ["--config=/etc/otel/config.yaml"]
    ports:
      - "4317:4317"   # OTLP gRPC
      - "55681:55681" # OTLP HTTP (可選)